package diego

// TODO: convert this to a static template file; doesn't have to be a Go string. Can embed it in the build.

const Template = `// Code generated by diego; DO NOT EDIT.

package {{ .Package }}

import (
	"errors"
	"flag"
	"fmt"

	"github.com/lukasschwab/diego/pkg/env"
)

// {{ .StructName }} generated from {{ .Source }}.
type {{ .StructName }} struct {
{{- range .Flags }}
	// --{{ .Name }}: {{ .Description }}
	{{ .GoName }} {{ .GoType }} ` + "`" + `json:"{{ .JSONName }},omitempty"` + "`" + `
{{- end }}
}

// Parse initializes the {{ .StructName }} from command-line and environment
// variables.
func (base *{{ .StructName }}) Parse(args []string) error {
	return errors.Join(
		base.foldEnv(),
		base.foldArgs(args),
	)
}

func (base *{{ .StructName }}) foldEnv() error {
	var err error
{{- range .Flags }}
	{{ .EnvLookup "err" }}
{{- end }}
	return err
}

func (base *{{ .StructName }}) foldArgs(args []string) error {
	fs := flag.NewFlagSet("{{ .StructName }}", flag.ContinueOnError)
{{- range .Flags }}
	fs.{{ .FlagVar }}(&base.{{ .GoName }}, "{{ .Name }}", base.{{ .GoName }}, "{{ .Description }}")
{{- end }}
	if err := fs.Parse(args); err != nil {
		return fmt.Errorf("failed to parse command line args: %w", err)
	}
	return nil
}
`
