// Code generated by diego; DO NOT EDIT.

package main

import (
	"errors"
	"flag"
	"fmt"

	"github.com/lukasschwab/diego/pkg/env"
)

// Parse initializes the DiegoVars from command-line and environment
// variables. Typically args should be os.Args[1:]; do not include the
// executable name.
func (base *DiegoVars) Parse(args []string) error {
	return errors.Join(
		base.foldEnv(),
		base.foldArgs(args),
	)
}

func (base *DiegoVars) foldEnv() error {
	var err error
	env.LookupString(&base.JsonFile, "DIEGO_JSON_FILE")
	env.LookupString(&base.Type, "DIEGO_TYPE")
	return err
}

func (base *DiegoVars) foldArgs(args []string) error {
	fs := flag.NewFlagSet("DIEGO", flag.ExitOnError)
	fs.StringVar(&base.JsonFile, "json-file", base.JsonFile, "relative path of the JSON file specifying command line args [DIEGO_JSON_FILE]")
	fs.StringVar(&base.Type, "type", base.Type, "name of the struct specifying command line args [DIEGO_TYPE]")
	if err := fs.Parse(args); err != nil {
		return fmt.Errorf("failed to parse command line args: %w", err)
	}
	return nil
}
