// Code generated by diego; DO NOT EDIT.

package main

import (
	"errors"
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"
)

// Parse initializes the DiegoVars from command-line and environment
// variables. Typically args should be os.Args[1:]; do not include the
// executable name.
func (base *DiegoVars) Parse(args []string) error {
	return errors.Join(
		base.foldEnv(),
		base.foldArgs(args),
	)
}

func (base *DiegoVars) foldEnv() error {
	var err error
	lookupString(&base.JsonFile, "DIEGO_JSON_FILE")
	lookupString(&base.StructType, "DIEGO_STRUCT_TYPE")
	return err
}

func (base *DiegoVars) foldArgs(args []string) error {
	fs := flag.NewFlagSet("DIEGO", flag.ExitOnError)
	fs.StringVar(&base.JsonFile, "json-file", base.JsonFile, "relative path of the JSON file specifying command line args [DIEGO_JSON_FILE]")
	fs.StringVar(&base.StructType, "struct-type", base.StructType, "name of the struct specifying command line args [DIEGO_STRUCT_TYPE]")
	if err := fs.Parse(args); err != nil {
		return fmt.Errorf("failed to parse command line args: %w", err)
	}
	return nil
}

// lookupString in environment; write to target if it's set.
func lookupString(target *string, name string) {
	read, ok := os.LookupEnv(name)
	if ok {
		*target = read
	}
}

// lookupInt in environment; write to target if it's set and parseable as a
// decimal int.
func lookupInt(target *int, name string) error {
	raw, ok := os.LookupEnv(name)
	if !ok {
		return nil
	}
	parsed, err := strconv.Atoi(raw)
	if err != nil {
		return fmt.Errorf("error parsing int environment variable '%s': %w", name, err)
	}
	*target = parsed
	return nil
}

// lookupBool in environment; write to target if it's set.
func lookupBool(target *bool, name string) error {
	raw, ok := os.LookupEnv(name)
	if !ok {
		return nil
	}
	truthiness := raw != "" && strings.ToLower(raw) != "false"
	*target = truthiness
	return nil
}
