// Code generated by diego; DO NOT EDIT.

package main

import (
	"errors"
	"flag"
	"fmt"

	"github.com/lukasschwab/diego/pkg/env"
)

// Parse initializes the ExampleVars from command-line and environment
// variables. Typically args should be os.Args[1:]; do not include the
// executable name.
func (base *ExampleVars) Parse(args []string) error {
	return errors.Join(
		base.foldEnv(),
		base.foldArgs(args),
	)
}

func (base *ExampleVars) foldEnv() error {
	var err error
	err = errors.Join(err, env.LookupBool(&base.Color, "EXAMPLE_COLOR"))
	err = errors.Join(err, env.LookupBool(&base.Verbose, "EXAMPLE_VERBOSE"))
	env.LookupString(&base.File, "EXAMPLE_FILE")
	err = errors.Join(err, env.LookupInt(&base.Workers, "EXAMPLE_WORKERS"))
	err = errors.Join(err, env.LookupBool(&base.ReadOnly, "EXAMPLE_READ_ONLY"))
	return err
}

func (base *ExampleVars) foldArgs(args []string) error {
	fs := flag.NewFlagSet("EXAMPLE", flag.ExitOnError)
	fs.BoolVar(&base.Color, "color", base.Color, "enable ANSI colors in CLI output [EXAMPLE_COLOR]")
	fs.BoolVar(&base.Verbose, "verbose", base.Verbose, "enable verbose logging [EXAMPLE_VERBOSE]")
	fs.StringVar(&base.File, "file", base.File, "path of file to process [EXAMPLE_FILE]")
	fs.IntVar(&base.Workers, "workers", base.Workers, "number of workers to use in parallel [EXAMPLE_WORKERS]")
	fs.BoolVar(&base.ReadOnly, "read-only", base.ReadOnly, "do not write output to file [EXAMPLE_READ_ONLY]")
	if err := fs.Parse(args); err != nil {
		return fmt.Errorf("failed to parse command line args: %w", err)
	}
	return nil
}

// ExampleVars generated from ./args.json.
type ExampleVars struct {
	// --color: enable ANSI colors in CLI output
	Color bool `json:"color,omitempty"`
	// --verbose: enable verbose logging
	Verbose bool `json:"verbose,omitempty"`
	// --file: path of file to process
	File string `json:"file,omitempty"`
	// --workers: number of workers to use in parallel
	Workers int `json:"workers,omitempty"`
	// --read-only: do not write output to file
	ReadOnly bool `json:"read-only,omitempty"`
}
